export { build } from './tasks/build'
export { clean } from './tasks/clean'
export { copy } from './tasks/copy'
export { dev } from './tasks/dev'
export { images } from './tasks/images'
export { pages } from './tasks/pages'
export { scripts } from './tasks/scripts'
export { serve } from './tasks/serve'
export { serve as default } from './tasks/serve'
export { styles } from './tasks/styles'
export { watch } from './tasks/watch'
