module.exports.build = require('./build')
module.exports.clean = require('./clean')
module.exports.copy = require('./copy')
module.exports.images = require('./images')
module.exports.scripts = require('./scripts')
module.exports.styles = require('./styles')
module.exports.templates = require('./templates')
