export { default as build } from './build'
export { default as clean } from './clean'
export { default as copy } from './copy'
export { default as images } from './images'
export { default as scripts } from './scripts'
export { default as serve } from './serve'
export { default as sprites } from './sprites'
export { default, default as start } from './start'
export { default as styles } from './styles'
export { default as templates } from './templates'
export { default as watch } from './watch'
