name: CI

on:
  push:
    branches: [master]

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - if: matrix.os == 'windows-latest'
        run: |
          npm config set msvs_version 2017
          npm config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"

      - run: npm ci

      - run: npm run lint

      - run: npm run check

      - run: npm run build
