name: CI

on:
  push:
    branches: [master]

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - run: npm ci

      - run: npm run lint

      - run: npm run format-check

      - run: npm run build
