name: CI

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: yarn

      - run: yarn build

      - run: yarn test
