name: CI

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: yarn

      - run: yarn test

      - run: yarn build
